[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
p21 = "8Re4KgcYHxU2zYb1jJ32a334aytW1bjUAgLyCHUGhqUt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "solana_wallets/wallet_0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
